trigger:
- none # Disable ci triggers.

pr: 
- none # Disable pull request triggers.

schedules:
- cron: "0 0 * * 0"
  displayName: Cron job every week
  branches:
    include:
    - main
  always: true

parameters:
- name: DAYS_UNTIL_EXPIRATION
  displayName: Indicate the number of days remaining after the App Registration secrets and certificates expires.
  type: string
  default: '30'

- name: INCLUDE_ALREADY_EXPIRED
  displayName: You also want to list secrets and certificates that have already expired. ?
  type: string
  default: 'No'

- name: TENANT_ID
  displayName: Your Tenant ID ?
  type: string
  default: '4389fecf-09b9-4e58-a8a1-60be4e33bcce'

- name: INCOMING_WEBHOOK
  displayName: Your Incoming Webhook connector ?
  type: string
  default: 'https://uniqueyanbal.webhook.office.com/webhookb2/4f546a25-a22c-4b3b-b456-82d16213775a@8cc9b063-d75c-433d-80d0-912c7c002e0b/IncomingWebhook/a3ac0fd3b57545a48cb11dc362683fc4/90dea4f4-2345-46b3-a66f-9fcd4e86bf9e/V2L7ZiOcH3Ppedtb1yCWigfe_3paRh1x6JHyHvogRAPoc1'

variables:
  INFRA_SERVICE_CONNECTION: 'srv-cnn-Monitoreo'
  DAYS_UNTIL_EXPIRATION: '${{ parameters.DAYS_UNTIL_EXPIRATION }}'
  INCLUDE_ALREADY_EXPIRED: '${{ parameters.INCLUDE_ALREADY_EXPIRED }}'
  TENANT_ID :  '${{ parameters.TENANT_ID }}'
  KeyVaultName: 'uat-msy-kv'
  INCOMING_WEBHOOK : '${{ parameters.INCOMING_WEBHOOK }}'

jobs:
  - job:
    displayName: Reporting Identity - App registrations
    pool:
      name: web-mex
    steps:
    - checkout: self

    - task: AzureKeyVault@2
      displayName: 'Azure Key Vault Infra'
      inputs:
        azureSubscription: $(INFRA_SERVICE_CONNECTION)
        KeyVaultName: $(KeyVaultName)
   
    - task: PowerShell@2
      displayName: Install Required Modules
      inputs:
        targetType: 'inline'
        script: |
          Install-Module -Name Az -Scope CurrentUser -Force -AllowClobber
          Install-Module -Name Microsoft.Graph -Scope CurrentUser -Force -AllowClobber
        pwsh: true

    - task: PowerShell@2
      displayName: Secrets and Certificates Reports - App Registrations Expiry
      inputs:
        targetType: 'filePath'
        filePath: 'Get-EntraAppRegistrations.ps1'
        pwsh: true
        arguments: '-DaysUntilExpiration $(DAYS_UNTIL_EXPIRATION) `
                    -IncludeAlreadyExpired $(INCLUDE_ALREADY_EXPIRED) `
                    -ClientId $(ClientID) `
                    -ClientSecret $(SecretID) `
                    -TenantId $(TENANT_ID) `
                    -hookUrl $(INCOMING_WEBHOOK) '

        errorActionPreference: 'stop'
